workflows:
    weather-tracker-workflow:
        name: WeatherTracker Workflow
        max_build_duration: 120
        instance_type: mac_mini_m2
        scripts:
            - name: CICD Started
              script: echo "Welcome to your CI/CD setup"
            - name: Build WeatherTracker
              script: |
                xcodebuild build \
                    -project "WeatherTracker.xcodeproj" \
                    -scheme "WeatherTracker" \
                    -sdk iphonesimulator \
                    -destination 'platform=iOS Simulator,name=iPhone 16 Pro,OS=18.2' \
                    -configuration Debug \
                    CODE_SIGN_IDENTITY="" \
                    CODE_SIGNING_REQUIRED=NO \
                    CODE_SIGNING_ALLOWED=NO
        publishing:
            email:
                recipients:
                    - khan.amjad36@gmail.com
